- package-lock.json
- package.json
- src/js/services/modal.js
- src/js/views/globals/modal/modal.hbs
- src/js/views/globals/modal/modal_views.js
- test/integration/services/modal.js
thought I'd get this up and try to get a review before the weekend. I know the tests are going to need changes, so fire away
> Test modals

- src/js/base/entity-service.js
- src/js/index.js
- src/js/services/auth.js
- test/fixtures/collections/groups.json
- test/fixtures/collections/patient-fields.json
- test/fixtures/collections/patients.json
- test/support/api/patient.js
- test/support/helpers/json-api.js
- test/support/index.js
- webpack.config.js
```js
describe('test', function() {
it('should run', function() {
cy
.server()
.routePatient()
.visit('/');
});
});
```
Then `$.ajax('/api/patients/1', Radio.request('auth', 'get:ajaxAuth'))` in the console
> Add initial data layer services and helpers

- src/js/services/auth.js
Just needs to wait for circleci to pass
> Add bearer token to prod until SSO

- src/js/entities-service/clinicians.js
- src/js/entities-service/entities/clinicians.js
- src/js/entities-service/entities/groups.js
- src/js/entities-service/entities/organizations.js
- src/js/entities-service/entities/patient-fields.js
- src/js/entities-service/entities/patients.js
- src/js/entities-service/entities/roles.js
- src/js/entities-service/entities/states.js
- src/js/entities-service/groups.js
- src/js/entities-service/index.js
- src/js/entities-service/organizations.js
- src/js/entities-service/patient-fields.js
- src/js/entities-service/patients.js
- src/js/entities-service/roles.js
- src/js/entities-service/states.js
> First pass of adding entity + service boilerplates

- .circleci/config.yml
> Configure Continuous Delivery for frontend

- .circleci/config.yml
> Remove testing branch from deploy jobs

- test/fixtures/config/actions.js
- test/fixtures/config/clinicians.js
- test/fixtures/config/organizations.js
- test/fixtures/test/roles.json
- test/fixtures/test/states.json
- test/plugins/faker-generator.js
- test/support/api/actions.js
- test/support/api/organizations.js
- test/support/index.js
think more need to be added? I wanted to get these up for review, and I can add more in + keep working on that setRelationship helper (was giving me trouble, so put it on pause for now).
> Adds fixtures + org and action api test helpers

- .eslintrc
- src/js/apps/patients/list/patients-all_app.js
- src/js/entities-service/entities/patients.js
- src/js/entities-service/patients.js
- src/js/views/patients/list/patients-all_views.js
- test/integration/components/optionlist.js
- test/integration/patients/list/patients-all.js
- test/integration/services/alert.js
- test/integration/services/modal.js
- test/plugins/faker-generator.js
- test/plugins/state-colors.js
- test/support/api/actions.js
- test/support/api/patients.js
- test/support/defaults.js
- test/support/index.js
> Basic all patients list

- package-lock.json
- package.json
- src/js/base/setup.js
- src/js/base/uuid.js
Not current covered so codecov is gonna complain, but we'll catch this with add action shortly.
> Add uuids to all new model.save

- src/js/apps/patients/view/view_app.js
- src/js/entities-service/actions.js
- src/js/entities-service/entities/actions.js
- src/js/entities-service/entities/events.js
- src/js/entities-service/events.js
- src/js/entities-service/index.js
- test/fixtures/config/events.js
- test/integration/patients/patient/view.js
- test/support/api/actions.js
> View list + deps

- cypress.json
- package.json
- src/js/apps/patients/patient/dashboard/dashboard_app.js
- src/js/apps/patients/patient/data-events/data-events_app.js
- src/js/apps/patients/patient/patient_app.js
- src/js/apps/patients/view/view_app.js
- src/js/base/app.js
- src/js/base/entity-service.js
- src/js/base/subrouterapp.js
- src/js/entities-service/actions.js
- src/js/entities-service/clinicians.js
- src/js/entities-service/entities/actions.js
- src/js/entities-service/entities/clinicians.js
- src/js/entities-service/organizations.js
- src/js/entities-service/patients.js
- src/js/i18n/en-US.yml
- src/js/views/patients/list/patients-all_views.js
- src/js/views/patients/patient/dashboard/dashboard_views.js
- src/js/views/patients/patient/data-events/data-events_views.js
- src/js/views/patients/patient/patient.scss
- src/js/views/patients/view/view-list.scss
- src/js/views/patients/view/view_views.js
- src/sass/modules/buttons.scss
- src/sass/modules/table-list.scss
- test/integration/patients/list/patients-all.js
- test/integration/patients/patient/patient.js
- test/integration/patients/patient/sidebar.js
- test/integration/patients/view.js
- test/support/api/actions.js
- test/support/api/patients.js
Not tested yet or fully implemented.  Can come back around
> Add patient dashboard

- .circleci/config.yml
> Add Pr Builds

- cypress.json
- src/js/views/patients/patient/dashboard/dashboard_views.js
- src/js/views/patients/view/view_views.js
Also a tiny commit removing a placeholder.  Probably doesn't belong here, but it's there and deal with it.
If this passes circle-ci hopefully the odd cross origin error is fixed?
Related:
https://github.com/cypress-io/cypress/issues/2448
https://github.com/tracim/tracim/issues/1727
https://github.com/cypress-io/cypress/issues/1951#issuecomment-465800679
> Disable chrome web security

- src/js/entities-service/clinicians.js
- src/js/entities-service/entities/clinicians.js
- src/js/services/auth.js
- test/fixtures/config/clinicians.js
- test/fixtures/test/organizations.json
- test/integration/globals/app-nav.js
- test/support/api/clinicians.js
> Use clinicians/me endpoint to bootstrap

- src/js/apps/patients/patient/dashboard/dashboard_app.js
- src/js/apps/patients/patient/patient_app.js
- src/js/apps/patients/patients-main_app.js
- src/js/apps/patients/sidebar/action-sidebar_app.js
- src/js/entities-service/entities/actions.js
- src/js/entities-service/entities/events.js
- src/js/entities-service/events.js
- src/js/services/sidebar.js
- src/js/views/patients/sidebar/action-sidebar.hbs
- src/js/views/patients/sidebar/action-sidebar.scss
- src/js/views/patients/sidebar/action-sidebar_views.js
- test/integration/patients/patient/patient.js
- test/support/api/events.js
- test/support/index.js
Adds action sidebar without styling, attributes or editing
> Introduce action sidebar

- .gitignore
- README.md
- package-lock.json
- package.json
- src/js/apps/patients/list/patients-all_app.js
- src/js/entities-service/patients.js
- src/js/index.js
- src/js/services/auth.js
- src/js/views/globals/app-nav/app-nav_views.js
- test/integration/patients/list/patients-all.js
- test/support/defaults.js
Possibly:
[1]: https://auth0.com/docs/libraries/auth0js/v9#extract-the-authresult-and-get-user-info
[2]: https://auth0.com/docs/libraries/auth0js/v9#using-checksession-to-acquire-new-tokens
> Require all access to be authenticated

- src/js/apps/patients/sidebar/action-sidebar_app.js
- src/js/base/helpers.js
- src/js/i18n/en-US.yml
- src/js/views/patients/sidebar/action-sidebar-activity-views.js
- src/js/views/patients/sidebar/action-sidebar_views.js
- test/fixtures/test/events.json
- test/integration/patients/sidebar/action-sidebar.js
- test/support/api/events.js
> Templates and views for various Action Event/Activity types

- src/js/apps/patients/sidebar/action-sidebar_app.js
- src/js/i18n/en-US.yml
- src/js/views/patients/sidebar/action-sidebar-activity-views.js
- src/js/views/patients/sidebar/action-sidebar.hbs
- src/js/views/patients/sidebar/action-sidebar_views.js
- test/fixtures/config/events.js
- test/fixtures/test/events.json
- test/integration/patients/sidebar/action-sidebar.js
> Display created and updated timestamps in action sidebar

- .circleci/config.yml
- deploy_tools/gh_comment
> Add tool to post comment to GH PR.

- src/js/apps/patients/patients-main_app.js
- src/js/apps/patients/view/view_app.js
- src/js/entities-service/actions.js
- src/js/i18n/en-US.yml
- src/js/views/globals/app-nav/app-nav_views.js
- src/js/views/patients/view/view_views.js
- test/integration/patients/view.js
> Adds hardcoded MVP action views (lists)

- src/js/apps/patients/view/view_app.js
- src/js/entities-service/entities/organizations.js
> Uses role id for CO role to filter actions

- src/js/apps/patients/patient/dashboard/dashboard_app.js
- src/js/apps/patients/patient/data-events/data-events_app.js
- src/js/entities-service/actions.js
I _think_ this is it? Given that the default of the patient actions endpoint is all non "done" status states?
> Filters data/events actions to only 'done'

- src/js/apps/globals/app-frame_app.js
- src/js/apps/patients/patients-main_app.js
- src/js/apps/patients/view/view_app.js
- src/js/entities-service/entities/clinicians.js
- src/js/i18n/en-US.yml
- src/js/views/globals/app-nav/app-nav_views.js
- src/js/views/patients/view/view_views.js
- test/integration/globals/app-nav.js
> Make app nav more data driven

- src/js/apps/patients/sidebar/action-sidebar_app.js
- src/js/components/droplist/index.js
- src/js/components/selectlist/index.js
- src/js/entities-service/entities/actions.js
- src/js/i18n/en-US.yml
- src/js/views/globals/app-frame.scss
- src/js/views/patients/actions/actions.scss
- src/js/views/patients/actions/actions_views.js
- src/js/views/patients/patient/dashboard/dashboard_views.js
- src/js/views/patients/patient/data-events/data-events_views.js
- src/js/views/patients/sidebar/action/action-details.hbs
- src/js/views/patients/sidebar/action/action-name.hbs
- src/js/views/patients/sidebar/action/action-sidebar-activity-views.js
- src/js/views/patients/sidebar/action/action-sidebar.hbs
- src/js/views/patients/sidebar/action/action-sidebar.scss
- src/js/views/patients/sidebar/action/action-sidebar_views.js
- src/sass/modules/buttons.scss
> Update action meta to be atomic saves

- src/js/apps/globals/app-frame_app.js
- src/js/views/globals/app-nav/app-nav_views.js
- test/integration/globals/app-nav.js
> Show which nav item is currently selected

- src/js/apps/globals/app-frame_app.js
- src/js/apps/patients/list/patients-all_app.js
- src/js/apps/patients/sidebar/action-sidebar_app.js
- src/js/apps/patients/view/view_app.js
- src/js/i18n/en-US.yml
- src/js/index.js
- src/js/views/globals/app-frame.scss
- src/js/views/globals/app-nav/app-nav.scss
- src/js/views/globals/app-nav/app-nav_views.js
- src/js/views/patients/list/patients-all_views.js
- src/js/views/patients/patient/dashboard/dashboard_views.js
- src/js/views/patients/patient/data-events/data-events_views.js
- src/js/views/patients/patient/patient.scss
- src/js/views/patients/sidebar/action/action-sidebar_views.js
- src/js/views/patients/view/view_views.js
- src/sass/modules/table-list.scss
- test/integration/globals/app-nav.js
- test/integration/services/alert.js
> Preloaders/tooltips/empty views/sidebar animation

- src/js/i18n/en-US.yml
- src/js/views/patients/sidebar/action/action-sidebar-activity-views.js
- test/fixtures/config/events.js
- test/fixtures/test/events.json
- test/integration/patients/sidebar/action-sidebar.js
I *think* this reflects the current state of action events. Dan is adding specific documentation for what they look like, so we can wait on that if we want.
> Fix action events display in sidebar

- src/js/services/auth.js
> Redirect to initially requested url after auth success

- src/js/apps/patients/patient/action/action_app.js
- src/js/i18n/en-US.yml
- src/sass/modules/fill-window.scss
- test/integration/patients/sidebar/action-sidebar.js
> Show error if action is not found

- config/webpack.env.js
- config/webpack.rules.js
- test/.eslintrc-ci
- test/plugins/index.js
> Fix CI linting

- src/js/views/patients/list/patients-all_views.js
- src/js/views/patients/patient/dashboard/dashboard_views.js
- src/js/views/patients/patient/data-events/data-events_views.js
- src/js/views/patients/view/view_views.js
- test/fixtures/config/actions.js
- test/integration/patients/list/patients-all.js
- test/integration/patients/patient/dashboard.js
- test/integration/patients/patient/data-and-events.js
- test/integration/patients/view.js
- Patient All list sorted by name
- Other 'action' views sorted by due date reverse chron (most current
first)
> Implement sort on various views

- package.json
- src/js/apps/patients/patient/dashboard/dashboard_app.js
- src/js/apps/patients/view/view_app.js
- src/js/i18n/en-US.yml
- src/js/views/patients/actions/actions_views.js
- src/sass/domain/action-state.scss
- test/fixtures/test/events.json
- test/fixtures/test/states.json
- test/integration/patients/patient/dashboard.js
- test/integration/patients/patient/data-and-events.js
- test/integration/patients/sidebar/action-sidebar.js
- test/integration/patients/view.js
* queued - To Do
* started - In Progress
* done - Done
> Switch to 3 states

- src/js/views/patients/patient/dashboard/dashboard_views.js
- src/js/views/patients/patient/data-events/data-events_views.js
- test/integration/patients/patient/dashboard.js
- test/integration/patients/patient/data-and-events.js
- if it's on dashboard and changed to done, animate out
- if it's on data & events and changed to !done, animate out
> Add animation to action removal from dashboard/data & events

- src/js/views/patients/sidebar/action/action-sidebar_views.js
- test/integration/patients/sidebar/action-sidebar.js
> Automatically focus new Action Title when sidebar opens

- .circleci/bin/update-gh-status
- .circleci/config.yml
> Update VersionSuffix to match backend practice

- src/assets/config.json
- src/js/app.js
- src/js/auth.js
- src/js/config.js
- src/js/entities-service/entities/organizations.js
- src/js/index.js
- test/integration/globals/app-nav.js
> Add instance config.json

- src/js/entities-service/entities/clinicians.js
- src/js/entities-service/entities/events.js
- src/js/i18n/en-US.yml
- src/js/views/patients/sidebar/action/action-sidebar-activity-views.js
- test/fixtures/config/events.js
- test/fixtures/test/clinicians.json
- test/fixtures/test/events.json
- test/integration/patients/sidebar/action-sidebar.js
- test/support/api/events.js
felt like there was a lot of "hand wavy" and "this'll do" going on while working on this...so...you know...
> Fixes action activity to use new data format

- src/js/views/patients/list/patients-all_views.js
- test/integration/patients/list/patients-all.js
> Sort group name on all patients list

- README.md
- composer.json
- package-lock.json
- package.json
- release/release.js
An example release made from the script https://github.com/RoundingWell/care-ops-frontend/tree/release/20191014
> Add FE release script

- src/js/index.js
> Update cypress e2e setup for access token

- package.json
- src/js/apps/globals/app-frame_app.js
- src/js/apps/programs/list/programs-all_app.js
- src/js/apps/programs/programs-main_app.js
- src/js/entities-service/entities/programs.js
- src/js/entities-service/index.js
- src/js/entities-service/programs.js
- src/js/i18n/en-US.yml
- src/js/views/programs/list/programs-all_views.js
- src/js/views/programs/list/programs-list.scss
- test/fixtures/config/programs.js
- test/integration/programs/list/programs-all.js
- test/support/api/programs.js
- test/support/index.js
> Add program list page

- package.json
- src/js/apps/globals/app-frame_app.js
- src/js/entities-service/entities/clinicians.js
- src/js/i18n/en-US.yml
- src/js/views/globals/app-nav/app-nav_views.js
- test/integration/globals/app-nav.js
left some comments in, as I'm sure there'll be requested changes and I can remove them on the next push
> Adds admin link to the top nav menu

- src/js/apps/forms/form/form_app.js
- src/js/apps/forms/forms-main_app.js
- src/js/i18n/en-US.yml
- src/js/views/forms/form/form.scss
- src/js/views/forms/form/form_views.js
- test/integration/forms/form.js
> Add form page sidebars and styling

- src/js/apps/globals/app-frame_app.js
- src/js/apps/globals/nav_app.js
- src/js/components/picklist/index.js
- src/js/components/picklist/picklist.scss
- src/js/entities-service/entities/clinicians.js
- src/js/i18n/en-US.yml
- src/js/views/globals/app-nav/app-nav.scss
- src/js/views/globals/app-nav/app-nav_views.js
- test/fixtures/test/clinicians.json
- test/integration/globals/app-nav.js
> Add navigation switching

- src/js/apps/admin/sidebar/program-sidebar_app.js
- src/js/i18n/en-US.yml
- src/js/views/admin/programs/sidebar/program-details.hbs
- src/js/views/admin/programs/sidebar/program-name.hbs
- src/js/views/admin/sidebar/program/program-details.hbs
- src/js/views/admin/sidebar/program/program-name.hbs
- src/js/views/admin/sidebar/program/program-sidebar.hbs
- src/js/views/admin/sidebar/program/programs-sidebar.scss
- src/js/views/admin/sidebar/program/programs-sidebar_views.js
- test/integration/admin/programs/sidebar/program-sidebar.js
Also updated some styles that were conflicting
This is probably going to be merge issues but we definitely had some css conflicts and this _I think_ completes the move
> Move program sidebar view

- src/js/i18n/en-US.yml
- src/js/views/patients/sidebar/action/action-sidebar-activity-views.js
- test/fixtures/test/events.json
- test/integration/patients/sidebar/action-sidebar.js
> Adds empty/null states for clearing duration/due action events

- src/js/apps/admin/program/action/action_app.js
- src/js/apps/admin/sidebar/program-sidebar_app.js
- src/js/apps/globals/nav_app.js
- src/js/apps/patients/patient/action/action_app.js
- src/js/apps/patients/view/view_app.js
- src/js/components/optionlist/index.js
- src/js/i18n/en-US.yml
- src/js/views/admin/program/program.scss
- src/js/views/admin/program/program_views.js
- src/js/views/admin/program/sidebar/program-sidebar.scss
- src/js/views/admin/program/sidebar/sidebar-layout.hbs
- src/js/views/admin/program/sidebar/sidebar-views.js
- src/js/views/admin/sidebar/action/action-sidebar_views.js
- src/js/views/admin/sidebar/program/program-sidebar.hbs
- src/js/views/admin/sidebar/program/program-state.hbs
- src/js/views/admin/sidebar/program/programs-sidebar.scss
- src/js/views/admin/sidebar/program/programs-sidebar_views.js
- src/js/views/patients/patient/dashboard/dashboard_views.js
- src/js/views/patients/patient/data-events/data-events_views.js
- src/js/views/patients/sidebar/action/action-sidebar_views.js
- src/sass/modules/buttons.scss
- test/integration/admin/programs/program/program.js
- test/integration/admin/programs/sidebar/program-sidebar.js
- test/integration/patients/patient/dashboard.js
- test/integration/patients/patient/data-and-events.js
I think some of the styles may be a little off, as per usual (in addition to anything else that may be a little off...)
> Edit program sidebar

- src/js/app.js
- src/js/apps/globals/app-frame_app.js
- src/js/apps/globals/error_app.js
- src/js/apps/patients/patients-main_app.js
- src/js/auth.js
- src/js/entities-service/entities/clinicians.js
- src/js/i18n/en-US.yml
- src/js/index.js
- src/js/views/globals/error/error.hbs
- src/js/views/globals/error/error_views.js
- test/integration/globals/error.js
> Handle error codes

- src/js/apps/admin/sidebar/action-sidebar_app.js
- src/js/apps/patients/sidebar/action-sidebar_app.js
- test/integration/admin/programs/sidebar/action-sidebar.js
- test/integration/patients/sidebar/action-sidebar.js
> Only save name and details attrs when saving action

- src/js/entities-service/entities/events.js
- src/js/views/patients/actions/actions_views.js
- test/fixtures/config/clinicians.js
- test/fixtures/test/clinicians.json
- test/integration/patients/sidebar/action-sidebar.js
`name` was added to clinician which broke the owner component cheat.
> Account for clinician name attribute

- .circleci/config.yml
> Update preview deploys to use fe/ directory

- src/js/apps/patients/patient/dashboard/add-action_app.js
- src/js/apps/patients/patient/dashboard/dashboard_app.js
- src/js/components/picklist/index.js
- src/js/components/picklist/picklist.scss
- src/js/entities-service/entities/actions.js
- src/js/entities-service/entities/program-actions.js
- src/js/entities-service/entities/programs.js
- src/js/entities-service/program-actions.js
- src/js/i18n/en-US.yml
- src/js/views/patients/patient/dashboard/add-action.scss
- src/js/views/patients/patient/dashboard/add-action_views.js
- src/js/views/patients/patient/dashboard/dashboard_views.js
- src/js/views/patients/patient/dashboard/layout.hbs
- test/integration/patients/patient/dashboard.js
- test/integration/patients/patient/patient.js
- test/integration/patients/sidebar/action-sidebar.js
- test/support/api/program-actions.js
getting this up so that it can be reviewed/taken over if needed.
> Adds new Add Action button to dashboard
